### ISSUE TITLE
Updating index.html has no effect

### ISSUE THREAD

**Issue by Artur-** [vaadin/base-starter-connect#43]
```
git clone git@github.com:vaadin/base-starter-connect.git
cd base-starter-connect
npm start
open http://localhost:8080
```

This shows a text field and a button, as expected.

Now remove the `<vaadin-*>` tags from index.html and save.
Webpack does some recompilation but http://localhost:8080 still shows the text field and button.

Stop the server, run `npm start` again. The page still contains a text field and a button.

**Comment by vlukashov** [comment]
The source of the confusion here is that during development hot reload and other features are provided by the dev server that runs on 8081 be default. The 8080 port is used for other purposes and does not support hot reloading.

There are 3 processes when the app is started in the dev mode
- the backend (currently defaults to 8080) and is intended for auth and RPC
- the frontend (currently defaults to 8081) and is intended for the browsers
- the API browser (currently defaults to 8082)

(in production there is only 1 process that handles both frontend and backend, and there is no API browser at all)

The proposal to fix this issue is to make the Vaadin Connect defaults closer to developer expectations and change the default ports arrangement in the dev mode to be:
- 8080: frontend (dev server)
- 8081: API browser
- 8082: backend

**Comment by Legioth** [comment]
Redefining the ports will only move the problem until you try the application in production mode and have to realize that you should then use port 8082 instead of 8080.

Isn't this yet another good reason to change the setup so that the Java-based SPA server would internally proxy to the WebPack server instead?

**Comment by vlukashov** [comment]
> Redefining the ports will only move the problem until you try the application in production mode and have to realize that you should then use port 8082 instead of 8080.
> 
> Isn't this yet another good reason to change the setup so that the Java-based SPA server would internally proxy to the WebPack server instead?

In production mode there only one port in use and it is 8080. I do not see that as a potential problem.

**Comment by Legioth** [comment]
So the Spring Boot application would be configured to listen to different ports depending on whether it's used in production or development?

**Comment by manolo** [comment]
This issue is fixed with https://github.com/vaadin/base-starter-connect/pull/51 
The change also handles to have only one port 8080 (the same for dev and prod modes) as was discussed here. 
The solution has a webpack process in running in watch mode, meaning that we don't use webpackserver, thus we don't need to proxy it, but it would be added in https://github.com/vaadin/base-starter-connect/pull/51 when transpiling performance becomes an issue.

Closing this, feel free to reopen if you consider this is still not fixed
