### ISSUE TITLE
avoid an unexpected login popup

### ISSUE THREAD

**Issue by vlukashov** [vaadin/base-starter-connect#47]
When evaluating the base starter it is unexpected that there is a Login prompt popup after I press the 'Greet' button.

To avoid confusion, let's make the `greet` method public, and add another method that greets the logged-in user (see the screen recording below.
![screen recording 2019-01-14 at 04 33 pm](https://user-images.githubusercontent.com/22416150/51119100-989aaa00-181a-11e9-92bf-4a54477352df.gif)

**Comment by platosha** [comment]
Since we have authentication for every backend method by default, should we have the login form in front of the entire app also?

What that would mean is that instead of offering authenticated actions right away, there would be a “Log in” link, and then, after successful login, the authenticated actions are disclosed? (Get a personal greeting).

This way seems more common to me.

**Comment by qtdzz** [comment]
# Updated DoD:
- Always show the login form when user is not logged in.
- Change the text field label, button text, service name and the response to whatever makes sense for authenticated user.
- Make sure that all the tests are still working
